config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :boards, only: [:index, :show, :create]

  root 'boards#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord

  validates :email, :name, :width, :height, :no_of_mines, presence: true

  delegate :has_mine?, to: :generated_board

  scope :recent, -> { order('created_at DESC').limit(10) }
  default_scope { order('created_at DESC') }

  def generated_board
    @generated_board ||= GenerateBoard.new(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @boards = Board.page(params[:page])
  end

  def create
    @board = Board.new(board_params)

    if @board.valid?
      @board.save

      redirect_to board_path(@board), notice: 'Board was successfully generated'
    else
      @boards = Board.recent
      render 'home', status: :unprocessable_entity
    end
  end

  def show
    @board = Board.find(params[:id])
  end

  def home
    @board = Board.new
    @boards = Board.recent
  end

  private

  def board_params
    params.require(:board).permit(:email, :name, :width, :height, :no_of_mines)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_board.html.erb
<tr>
  <td><%= board.id %></td>
  <td><%= link_to board.name, board_path(board) %></td>
  <td><%= board.email %></td>
  <td><%= board.created_at.strftime('%I:%M %p  %B %d, %Y') %></td>
</tr>

app/views/boards/_form.html.erb
<%= simple_form_for @board do |f| %>
  <%= f.input :email %>
  <%= f.input :name, label: 'Board Name' %>
  <%= f.input :width %>
  <%= f.input :height %>
  <%= f.input :no_of_mines %>
  <div class="row">
    <div class="col d-grid">
      <%= f.submit 'Generate Board', class: 'btn btn-outline-success btn-block' %>
    </div>
  </div>
<% end %>

app/views/boards/home.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Create Minessweeper Board</span>
      </div>
      <div class="card-body">
        <%= render 'form' %>
      </div>
    </div>

    <div class="card mt-5">
      <div class="card-header d-flex justify-content-between">
        <span>10 most recently generated boards</span>
      </div>
      <div class="card-body">
        <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
            <th>Board Name</th>
            <th>Email</th>
            <th>Created At</th>
          </thead>
          <tbody>
            <%= render @boards %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex justify-content-center pt-3">
        <%= link_to 'View all generated boards', boards_path, class: 'btn btn-outline-success btn-block' %>
      </div>
    </div>
  </div>
</div>

app/views/boards/index.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Boards</span>
      </div>
      <div class="card-body">
        <table class="table table-striped table-hover">
          <thead>
            <th>ID</th>
            <th>Board Name</th>
            <th>Email</th>
            <th>Created At</th>
          </thead>
          <tbody>
            <%= render @boards %>
          </tbody>
        </table>
      </div>
      <div class="card-footer d-flex justify-content-center pt-3">
        <%= paginate @boards %>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <span>Board: <%= @board.name %></span>
        <p>
          <strong>Creator:</strong>
          <spam><%= @board.email %></spam>
        </p>
      </div>
      <div class="card-body">
        <table class="table table-bordered board">
          <tbody>
            <% (0...@board.width).map do |x| %>
              <tr>
                <% (0...@board.height).map do |y| %>
                  <td width="<%= (1.to_f/@board.width) * 100 %>%" height="<%= (1.to_f/@board.height) * 100 %>%">
                    <div class="slot">
                      <% if @board.has_mine?(x: x, y: y) %>
                        <%= image_tag('bomb.png') %>
                      <% else %>
                        <%= image_tag('no-bomb.png') %>
                      <% end %>
                    </div>
                  </td>
                <% end %>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minesweeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true, type: "module" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="header">
      <%= render 'shared/header' %>
    </div>
    <div class="body-content pt-3">
      <div class="container-fluid">
        <%= render 'shared/flash' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show mt-3 mb-3" role="alert">
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show mt-3 mb-3" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Minesweeper Exam</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
        <li class="nav-item">
          <%= link_to 'Boards', boards_path, class: 'nav-link', aria: { current: 'page' } %>
        </li>
      </ul>
    </div>
  </div>
</nav>